development:
  adapter: postgresql
  encoding: utf8
  database: react_database_development
  pool: 5
  username:
  password:

test: 
  adapter: postgresql
  encoding: utf8
  database: react_database_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: react_database_production
  pool: 5
  username:
  password:
